name: Pin Dependabot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/sethvargo/ratchet:0.2.0
    name: Test job
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.0 ratchet:actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: |-
          ratchet pin .github/workflows/test.yml
          ratchet pin .github/workflows/test-anser.yml
          cat .github/workflows/test.yml
          cat .github/workflows/test-anser.yml
